Two changes for catkin_make to compile under gta-robotics docker: (error: 'vector' does not name a type) vector compression_params; to: std::vector compression_params;
and needed to add:
(error: 'imshow' is not a member of 'cv')
include <opencv2/highgui/highgui.hpp>